Add centos support

diff --git a/openjdk11/s2i/bin/assemble b/openjdk11/s2i/bin/assemble
--- a/openjdk11/s2i/bin/assemble
+++ b/openjdk11/s2i/bin/assemble
@@ -67,10 +67,21 @@ exit $ERR
 fi
 
 echo "---> COPY GENERATE APP TO DEPLOY DIR..."
-find . -name '*-thorntail.jar' | xargs cp -t . &> /dev/null || find . -name '*-swarm.jar' | xargs cp -t . &> /dev/null || find . -name '*-bootable.jar' | xargs cp -t . &> /dev/null && mv *.jar /opt/app-root/app.jar && \
+find . -name '*-thorntail.jar' | xargs cp -t . &> /dev/null || find . -name '*-swarm.jar' | xargs cp -t . &> /dev/null || find . -name '*-bootable.jar' | xargs cp -t . &> /dev/null && mv *.jar /opt/app-root/app.jar
+
+jar=`ls -1 /opt/app-root/app.jar 2>/dev/null | wc -l`
+
+if [ $jar == 0 ]; then
+echo "---> APP JAR NOT FOUND!"
+exit 1
+fi
+
 ls -lh /opt/app-root && echo "---> APP INSTALL OK!"
+
 echo "---> FIX PERMISSIONS DIR"
 /usr/libexec/s2i/fix /opt
 /usr/libexec/s2i/fix /home/s2i
+
 cd $HOME && rm -rf /opt/src
+
 echo "---> INSTALL FINISH"
